# Generated by Django 3.1.12 on 2026-04-19 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Index GIN sur contenu de Question → recherche rapide
            sql="""
                CREATE INDEX IF NOT EXISTS idx_question_contenu_gin
                ON question USING GIN (contenu);

                CREATE INDEX IF NOT EXISTS idx_reponse_donnee_gin
                ON reponse USING GIN (reponse_donnee);

                CREATE INDEX IF NOT EXISTS idx_categorie_structure_gin
                ON categorie USING GIN (structure_questions);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_question_contenu_gin;
                DROP INDEX IF EXISTS idx_reponse_donnee_gin;
                DROP INDEX IF EXISTS idx_categorie_structure_gin;
            """
        )
    ]

